module.exports = {
  apps: [
    {
      name: 'ac-heating-web',
      script: 'npm',
      args: 'run start',
      cwd: '/home/leos/ac-heating-web-new',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        ADMIN_BYPASS_AUTH: 'true',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: 3000,
        ADMIN_BYPASS_AUTH: 'true',
      },
      error_file: '/home/leos/ac-heating-web-new/logs/pm2-error.log',
      out_file: '/home/leos/ac-heating-web-new/logs/pm2-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
    {
      name: 'ac-heating-dev',
      script: 'npm',
      args: 'run dev',
      cwd: '/home/leos/ac-heating-web-new',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'development',
        PORT: 3100,
        TURBOPACK: '1',
      },
      error_file: '/home/leos/ac-heating-web-new/logs/pm2-dev-error.log',
      out_file: '/home/leos/ac-heating-web-new/logs/pm2-dev-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      min_uptime: '10s',
      max_restarts: 10,
      restart_delay: 4000,
    },
  ],
};
